worker_num: 2
TrainReader:
  inputs_def:
    fields: ['image', 'im_info',  'im_id', 'gt_bbox', 'gt_class', 'gt_score', 'is_crowd']
  sample_transforms:
  - DecodeImage: {to_rgb: true}
  - RandomFlipImage: {prob: 0.5}
  - NormalizeImage: {is_channel_first: false, is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeImage: {target_size: 800, max_size: 1333, interp: 1, use_cv2: true}
  - Permute: {to_bgr: false, channel_first: true}
  batch_transforms:
  - PadBatch: {pad_to_stride: 128, use_padded_im_info: false}
  - Gt2FCOSTarget: {object_sizes_boundary: [64, 128, 256, 512], center_sampling_radius: 1.5, downsample_ratios: [8, 16, 32, 64, 128], norm_reg_targets: True}
  batch_size: 2
  shuffle: true
  drop_last: false


EvalReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id']
  sample_transforms:
  - DecodeOp: {}
  - NormalizeImageOp: {mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeOp: {interp: 1, target_size: [800, 1333], keep_ratio: True}
  - PermuteOp: {}
  batch_transforms:
  - PadBatchOp: {pad_to_stride: 128}
  batch_size: 1
  shuffle: false


TestReader:
  inputs_def:
    fields: ['image', 'im_shape', 'scale_factor', 'im_id']
  sample_transforms:
  - DecodeOp: {}
  - NormalizeImageOp: {mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - ResizeOp: {interp: 1, target_size: [1333, 800], keep_ratio: True}
  - PermuteOp: {}
  batch_transforms:
  - PadBatchOp: {pad_to_stride: 128}
  batch_size: 1
  shuffle: false

